name: Build and Deploy News Site

on:
  # Bu, GitHub Actions arayüzünden manuel olarak iş akışını çalıştırmanıza olanak tanır.
  workflow_dispatch:

  # Bu, iş akışının belirli bir takvime göre otomatik olarak çalışmasını sağlar.
  # Her gün UTC saatiyle 03:00'te çalışır. API limitlerinizi göz önünde bulundurarak bu saati ayarlayabilirsiniz.
  schedule:
    - cron: '0 3 * * *' 

  # Bu, ana brança (main) her push yapıldığında iş akışını çalıştırır.
  # Eğer sadece zamanlanmış çalıştırma istiyorsanız bu bloğu kaldırabilirsiniz.
  push:
    branches:
      - main # Ana brançınızın adı neyse onu kullanın (genellikle 'main' veya 'master')

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # İş akışının çalışacağı işletim sistemi

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # submodules: true # Temayı submodule olarak yönetmiyorsak bu satırı kaldırıyoruz veya 'false' yapıyoruz.
          # Eğer yukarıdaki "Temayı Normal Dizin Gibi Yönetme" çözümünü uyguladıysanız bu satır kapalı kalmalı.
          fetch-depth: 0   # Git geçmişinin tamamını çeker, bu Hugo'nun bazı özelliklerini destekleyebilir.

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' # Kullandığınız Python sürümünü belirtin (ör: '3.9', '3.10', '3.11')

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          # Eğer projenizde requirements.txt varsa aşağıdaki satırı kullanın (önerilir!)
          # pip install -r requirements.txt
          # Gerekli kütüphaneleri manuel olarak yükle
          pip install Flask requests apscheduler python-dotenv

      - name: Run News Bot (Fetch News & Generate Hugo Content)
        env:
          # GitHub Secrets'tan API anahtarını ortam değişkeni olarak sağlar.
          WORLD_NEWS_API_KEY: ${{ secrets.WORLD_NEWS_API_KEY }}
        run: |
          # Flask sunucusunu başlatmadan, haber çekme ve Hugo içeriği oluşturma mantığını doğrudan çağırıyoruz.
          # news_bot.py dosyasındaki 'run_news_processing_and_build' fonksiyonunu Python komutuyla çalıştır.
          # Bu komut, 'my_news_site_bot' ana dizininde çalışır.
          python -c "from news_bot import run_news_processing_and_build; run_news_processing_and_build()"
        # working-directory: ${{ github.workspace }} # Varsayılan olarak repo kök dizininde çalışır, bu satır gereksiz.

      - name: Build Hugo Site
        # Hugo'nun 'static_site' klasörü içinde çalışmasını sağlar
        working-directory: static_site 
        run: |
          # Hugo CLI aracını indir ve kur (Ubuntu için .deb paketi)
          # Kullandığınız Hugo sürümünü ve işletim sistemini kontrol edin.
          wget https://github.com/gohugoio/hugo/releases/download/v0.92.2/hugo_extended_0.92.2_Linux-64bit.deb -O /tmp/hugo.deb
          sudo dpkg -i /tmp/hugo.deb
          
          # Hugo sitesini derle. -D taslakları da dahil eder.
          hugo -D

      - name: Deploy to GitHub Pages
        # GitHub Pages'e derlenmiş siteyi dağıtmak için popüler bir action
        uses: peaceiris/actions-gh-pages@v4
        with:
          # GitHub tarafından sağlanan varsayılan bir token, dağıtım için yetkilidir.
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Hugo'nun derlenmiş çıktısının bulunduğu dizin. 
          # Burası `static_site` klasörünün içindeki `public` klasörüdür.
          publish_dir: ./static_site/public 
          # GitHub Pages'i yayınladığınız branş. 
          # Eğer "main" branşından yayınlıyorsanız bu satırı yorum satırı bırakın.
          # Varsayılan olarak 'gh-pages' branşına dağıtır.
          # publish_branch: gh-pages