name: Build and Deploy News Site

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *' # Günlük 03:00 UTC
  push:
    branches:
      - main 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0   

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' 

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Flask requests apscheduler python-dotenv

      - name: Run News Bot (Fetch News & Build Hugo Content)
        env:
          WORLD_NEWS_API_KEY: ${{ secrets.WORLD_NEWS_API_KEY }}
        run: |
          # Flask sunucusunu başlatmadan, haber çekme ve Hugo içeriği oluşturma mantığını doğrudan çağır.
          # news_bot.py içindeki run_news_processing_and_build fonksiyonunu kullanıyoruz.
          python -c "from news_bot import run_news_processing_and_build; run_news_processing_and_build()"
        working-directory: ${{ github.workspace }} # Botun kendi kök dizininde çalışmasını sağla

      - name: Build Hugo Site
        working-directory: static_site # Hugo'nun çalışacağı dizini belirt
        run: |
          # Hugo'yu yükle (Gerekli versiyonu seçin)
          wget https://github.com/gohugoio/hugo/releases/download/v0.92.2/hugo_extended_0.92.2_Linux-64bit.deb
          sudo dpkg -i hugo_extended_0.92.2_Linux-64bit.deb

          # Hugo sitesini derle
          hugo -D

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./static_site/public # Hugo'nun çıktısının olduğu dizin (repo köküne göre)
          # publish_branch: gh-pages # Eğer GitHub Pages'i farklı bir branştan yayınlıyorsanız bu satırı aktif edin
